[package]
name = "marcys"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sys_metrics = "0.2"
serde = "1.0"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
